### ISSUE TITLE
No such file or directory: './misc/log/CartPole-DPGPMM-20-23-01.npy'

### ISSUE THREAD

**Issue by lylyjy** [mxu34/mbrl-gpmm#1]
Traceback (most recent call last):
  File "E:/google下载/mbrl-gpmm-master/train_on_swingup.py", line 204, in <module>
    np.save(path, log, allow_pickle=True)
  File "<__array_function__ internals>", line 6, in save
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 524, in save
    file_ctx = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: './misc/log/CartPole-DPGPMM-20-23-01.npy'

Process finished with exit code 1

How to solve it ?Thanks

**Comment by mxu34** [comment]
Please add a log folder inside the misc folder.
